---
abstract: 'Get your feet died blue (metaphorically of course).'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-BLUEFEET
recommends:
  DateTime: 0
  List::AllUtils: 0
  Path::Class: 0
requires:
  CHI: 0
  Catalyst: 0
  DBIx::Class: 0
  DBIx::ResultSet: 0
  Module::Load: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::Types: 0
  Test::More: 0
  autodie: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-BLUEFEET
  repository: http://github.com/bluefeet/Task-BeLike-BLUEFEET
version: 0.01
